export enum TemplateEnum {
    remoteDataSource,
    repositoryConcrete,
    repository,
    useCase,
    blocBloc,
    blocEvent,
    blocState,
    imports,
    coreImports,
    entity,
    exception,
    failure,
    model,
    coreUseCase,
    sharedImports,
    basicBlocStates,
    localDataSource
}